# cluster-infra/templates/adsb-alerts-secret.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  # Name of the external secret inside k8s
  name: adsb-alerts-secret
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: infisical-backend
    kind: SecretStore
  target:
    # name of the secret object inside k8s, referenced by deployment
    name: adsb-alerts-secret
    template:
      engineVersion: v2
  data:
  - secretKey: discord_webhhok_adsb_alerts
    remoteRef:
      key: discord_webhhok_adsb_alerts

