apiVersion: v1
kind: ConfigMap
metadata:
  name: adsb-alerts-config
  labels:
    app: adsb-alerts
    component: config
data:
  filters.json: |
    {
      "test_baltic_icao" : {
        "metadata": {
          "filter_text": "US Navy maritime patrol and reconnaissance",
          "status": "enabled"
        },
        "hex": "ae688d",
        "filter": "baltic"
      },
      "lla_no_filter": {
        "metadata": {
          "filter_text": "Spotted at LLA",
          "status": "disabled"
        },
        "filter": "lla_no_filter"
      },
      "vip_no_filter": {
        "metadata": {
          "filter_text": "NATO AEW&C component"
        },
        "filter": "vip_no_filter"
      },
      "re_test_1": {
        "metadata": {
          "status": "enabled",
          "filter_text": "Test regex matching LLA"
        },
        "filter": "lla_no_filter",
        "flight": "SAS\\d+"
      },
      "re_test_2": {
        "metadata": {
          "status": "disabled",
          "filter_text": "Test regex matching in-situ"
        },
        "filter": "in-situ",
        "flight": "SAS\\d+"
      },
      "in_situ_alert_all": {
        "metadata": {
          "status": "disabled",
          "filter_text": "Seen by the local RTL-SDR"
        },
        "filter": "in-situ"
      }
    }
