apiVersion: v1
kind: ConfigMap
metadata:
  name: adsb-alerts-config
  labels:
    app: adsb-alerts
    component: config
data:
  filters.json: |
    {
      "test_baltic_icao" : {
        "hex": "ae688d",
        "filter": "baltic",
        "filter_text": "US Navy maritime patrol and reconnaissance"
      },
      "local_sas": {
        "flight": "SAS010",
        "filter": "in-situ",
        "filter_text": "Seen by the local RTL-SDR dawg"
      },
      "hormuz_test": {
        "hex": "ae63be",
        "filter": "hormuz",
        "status": "disabled"
      },
      "lla_no_filter": {
        "filter": "lla_no_filter",
        "status": "disabled",
        "filter_text": "Spotted at LLA"
      },
      "bc_no_filter": {
        "filter": "bc_no_filter",
        "status": "disabled"
      },
      "vip_no_filter": {
        "filter": "vip_no_filter",
        "filter_text": "NATO AEW&C component"
      },
      "re_test_1": {
        "metadata": {
          "status": "enabled",
          "filter_text": "Test regex matching LLA"
        },
        "filter": "in-situ",
        "flight": "SAS\d+",
      }
      "re_test_2": {
        "metadata": {
          "status": "enabled",
          "filter_text": "Test regex matching in-situ"
        },
        "filter": "in-situ",
        "flight": "SAS\d+",
      }
    }
