apiVersion: v1
kind: ConfigMap
metadata:
  name: adsb-alerts-config
  labels:
    app: adsb-alerts
    component: config
data:
  filters.json: |
    {
      "test_icao": {
        "hex": "ae07ec"
      },
      "test_baltic_icao" : {
        "hex": "ae688d",
        "filter": "baltic"
      },
      "local_sas": {
        "flight": "SAS010",
        "filter": "in-situ",
        "filter_text": "Seen by the local RTL-SDR dawg"
      },
      "local_sas_2": {
        "flight": "SAS019",
        "filter": "in-situ"
      },
      "hormuz_test": {
        "hex": "ae63be",
        "filter": "hormuz"
      },
      "lla_no_filter": {
        "filter": "lla_no_filter",
        "status": "disabled"
      },
      "bc_no_filter": {
        "filter": "bc_no_filter"
      }
    }
