# adsb-decoder/templates/adsb-location-secret.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  # Name of the external secret inside k8s
  name: adsb-location-secret
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: infisical-backend
    kind: SecretStore
  target:
    # name of the secret object inside k8s, referenced by deployment
    name: adsb-location-secret
    template:
      engineVersion: v2
  data:
  - secretKey: location_lat
    remoteRef:
      key: location_lat
  - secretKey: location_lon
    remoteRef:
      key: location_lon
  - secretKey: location_alt
    remoteRef:
      key: location_alt

