apiVersion: apps/v1
kind: Deployment
metadata:
  name: adsb-api-deployment
  labels:
    app.kubernetes.io/name: adsb-api
    app.kubernetes.io/component: api
spec:
  replicas: 1 
  selector:
    matchLabels:
      app.kubernetes.io/name: adsb-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: adsb-api
    spec:
      containers:
        - name: adsb-api
          image: adsb-api:local
          imagePullPolicy: IfNotPresent
          env:
            - name: LOG_LEVEL
              value: "INFO"
            - name: INGESTOR_URL
              value: "http://adsb-ingestor-service:8000/api/v1/enrich"
          ports:
            - containerPort: 8080
          command: ["python"]
          args: ["adsb-api/main.py"]
          # Resource limits 
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            # This name refers to the storage block to grab and mount in the file system of this container
            - name: adsb-api-config
              mountPath: /app/adsb-api/config.json
              subPath: config.json
              readOnly: true
      volumes:
        # This name defines the identity of the storage volume at the pod level
        - name: adsb-api-config
          configMap:
            # This is the name of the configmap in the Helm chart
            name: adsb-api-config
---
apiVersion: v1
kind: Service
metadata:
  name: adsb-api-service
spec:
  selector:
    app.kubernetes.io/name: adsb-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

