apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: infisical-backend
spec:
  provider:
    webhook:
      url: "https://app.infisical.com/api/v3/secrets/raw/{{ .remoteRef.key }}?workspaceId=2882cdfb-9c15-4173-a0d5-454b681c915d&environment=dev"
      headers:
        Authorization: "Bearer {{ .infisical_token }}"
      secrets:
        - name: infisical_token
          secretRef:
            name: infisical-auth
            key: clientSecret
