apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  # Name of the external secret inside k8s
  name: adsb-db-secret
spec:
  target:
    # name of the secret object inside k8s, referenced by deployment
    name: adsb-db-credentials 
    template:
      engineVersion: v2
      data:
        # Construct the DSN using both fetched variables
        database_dsn: "postgresql://{{ .db_user }}:{{ .db_password }}@adsb-db-service:5432/adsb"
  data:
  - secretKey: db_password
    remoteRef:
      key: path/to/your/vault/db-creds
      property: password
  - secretKey: db_user
    remoteRef:
      key: path/to/your/vault/db-creds
      property: username
