filters:
  vip_icaos:
    - 8960b1
    - 4aecd2
    - 0a4026
endpoints:
  airplanesLive:
    mil: "https://api.airplanes.live/v2/mil"
    lla: "https://api.airplanes.live/v2/point/65.543908/22.121288/2"
