# cluster-infra/templates/adsb-db-secret.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  # Name of the external secret inside k8s
  name: adsb-db-credentials
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: infisical-backend
    kind: SecretStore
  target:
    # name of the secret object inside k8s, referenced by deployment
    name: adsb-db-credentials 
    template:
      engineVersion: v2
      data:
        # Construct the DSN using both fetched variables, include them so they are not overwritten
        database_dsn: "postgresql://{{ "{{ .db_user }}" }}:{{ "{{ .db_password }}" }}@adsb-db-postgresql:5432/adsb"
        db_user: "{{ "{{ .db_user }}" }}"
        db_password: "{{ "{{ .db_password }}" }}"
  data:
  - secretKey: db_password
    remoteRef:
      key: db_password
  - secretKey: db_user
    remoteRef:
      key: db_user

